author: thewhiteh4t

title: The White Circle | Open Cyber Security Community

description: >-
  The White Circle is a community for Cyber/Information Security students, enthusiasts and professionals. You can discuss anything related to Security, share your knowledge with others, get help when you need it and proceed further in your journey with amazing people from all over the world.

baseurl: "/"

url: "https://twcircle.com"

discord: "https://discord.gg/MtKK7U4"

plugins:
  - jekyll-feed
  - jekyll-sitemap